//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllOrdersDetail
    {
        public string Firstname { get; set; }
        public string Clinicname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<double> Productprice { get; set; }
        public Nullable<int> Productqty { get; set; }
        public Nullable<double> Productamount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProductName { get; set; }
        public int Id { get; set; }
    }
}
