//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string Imagename { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> Educationid { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Product Product { get; set; }
    }
}
