//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int Id { get; set; }
        public Nullable<int> Orderid { get; set; }
        public Nullable<int> Productid { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Productprice { get; set; }
        public Nullable<int> Productqty { get; set; }
        public Nullable<double> Productamount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
