//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliedProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuppliedProduct()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> GrandAmount { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
